### ISSUE TITLE
ModuleNotFoundError: No module named 'metadata'

### ISSUE THREAD

**Issue by llxyw** [ZhenyueQin/Angular-Skeleton-Encoding#3]
您好，我在运行bash train.sh时出现了以下错误
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    from utils_dir.utils_result import get_result_confusion_jsons
  File "/home/liuwen/Angular-Skeleton-Encoding/utils_dir/utils_result.py", line 6, in <module>
    from metadata.class_labels import ntu120_code_labels, anu_bullying_pair_labels, bly_labels, anubis_ind_actions
ModuleNotFoundError: No module named 'metadata'
是缺少标签类的包吗？可以提供一下吗，谢谢

**Comment by Nothing1024** [comment]
试着把`metadata.` 删除 项目里面没有发现本地metadata
